title: Dilip's Portfolio
author: dilipsolanki1020
email: dilipsolanki1020@gmail.com

theme: minima
description: > # this means to ignore newlines until "baseurl:"
 This is my personal portfolio site.sfd h

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
